name: ValorGuideBuild

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build With Gradle
        uses: eskatos/gradle-command-action@v1
        with:
          args: build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ValorGuideAndStats.apk
          path: app/build/outputs/apk/apk-debug.apk
